config/routes.rb
Rails.application.routes.draw do
      resources :authors
        resources :posts
        
        root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author

  validates :title, presence: :true
  validates :body, presence: :true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :set_authors, only: [:show, :edit]

    def index
        @authors = Author.all
    end

    def show
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
            if @author.save
                 flash[:notice] = "Successfully created author!"
                 redirect_to author_path(@author)
            else
                 flash[:alert] = "Error creating new author !"
                render :new
            end

    end

    def update
        @author = Author.new
            if @author.update(author_params)
                 flash[:notice] = "Successfully created post!"
                 redirect_to author_path(@author)
            else
                 flash[:alert] = "Error creating new post!"
                render :new
            end
    end

    def edit
    end

    def destroy
        
    end

    private

    def set_authors
        @author = Author.find(params[:id])
    end

    def author_params
        params.require(:author).permit(:name)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_posts, only: [:show, :edit]

    def index
        @posts = Post.all.limit(5).order('created_at DESC')
    end

    def show
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
            if @post.save
                flash[:notice] = "Successfully created post!"
                redirect_to post_path(@post)
            else
                flash[:alert] = "Error creating new post!"
                render :new
            end    
    end


    private

    def set_posts
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :body, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/index.html.erb
<h1>Author listing</h1>

        <% @authors.each do |author| %>
           <strong> Author name: </strong> <%= author.name %><br />
           <%= link_to 'show', author %><br />
        <% end %>

<br />
<hr>

<%= link_to 'Add new Author', new_author_path %>

app/views/authors/new.html.erb
<h1>Add new Author</h1>
<%= form_for (@author) do |f| %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %><br />
    </div>

    <div class="action">
    <%= f.submit "Create author" %>
    </div>
<% end %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show data</h1>

<strong>Author name: </strong><%= @author.name %><br />


<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiveMinV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts Listing</h1>
<hr>

<% @posts.each do |post| %>
    <strong>Title: </strong><%= post.title %><br />
    <strong>Body: </strong><%= post.body%><br />
    <strong>Created at: </strong><%= post.created_at.strftime("%d-%m-%Y") %><br />
     <%= link_to 'show', post %><br />
     <hr>

<br />
<% end %>

<%= link_to 'Add new Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Add new Post</h1>
    <%= form_for (@post) do |f| %>
        <div class="field">
            <%= f.label :title %> <br />
            <%= f.text_field :title %><br />
        </div>

        <div class="field">
            <%= f.label :body %> <br />
            <%= f.text_area :body %><br />
        </div>

         <div class="field">
            <%= f.label :author %> <br />
            <%= f.select :author_id, Author.all.collect { |p| [ p.name, p.id ] }, blank: 'Pick someone' %><br />
        </div>


        <div class="action">
            <%= f.submit  %>
        </div>
    <% end %>

<%= link_to 'Back', authors_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show posts</h1>

<strong>Title: </strong><%= @post.title %><br />
<strong>Body: </strong><%= @post.body %><br />
<strong>Author by: </strong><%= @post.author.name %><br />


<%= link_to 'Back', posts_path %>